[package]
name = "tea-actor-utility"
version = "0.0.1"
authors = ["jacky.li <liyangwood@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]

wascc-actor = "0.7.1"

# serde = "1.0.106"
# serde_json = "1.0.51"
# serde_derive = "1.0.106"
# rmp-serde = "0.14.3"
# lazy_static = "1.4.0"

